spring:
  datasource:
      username: root-prd
      password: admin-prd
      url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  
  jpa:
    hibernate:
      ddl-auto: update