spring:
  datasource:
      username: root
      password: admin
      url: jdbc:mysql://localhost:3306/transportador?useTimezone=true&serverTimezone=UTC
  
  jpa:
    hibernate:
      ddl-auto: update
